/* ----------------------------------------------------------------------------
 * Project template files for the FlixelGDX project generator.
 *
 * Each builder returns a record of `{relativePath: fileContents}` that we feed
 * into JSZip. We intentionally generate textual files (build scripts, Java /
 * Groovy / Kotlin sources, settings.gradle etc) instead of bundling binary
 * Gradle wrapper jars — modern Gradle can bootstrap the wrapper jar via
 * `gradle wrapper`, which is documented in the generated README.
 * --------------------------------------------------------------------------- */

export type Language = 'java' | 'groovy' | 'kotlin';
export type IDE = 'idea' | 'eclipse' | 'vscode' | 'none';
export type Template = 'blank' | 'platformer';
export type Platform = 'desktop' | 'web' | 'android' | 'ios';

export interface GeneratorOptions {
  gameName: string;
  gameId: string;
  packageName: string;
  language: Language;
  javaVersion: number;
  flixelVersion: string;
  ide: IDE;
  template: Template;
  platforms: Platform[];
  expert: boolean;
  heapMb: number;
  jvmFlags: string;
  gradleConfig: string;
}

const GROOVY_LINE = "\n";

/* -------------------------- gradle.properties ----------------------------- */
function gradleProperties(o: GeneratorOptions): string {
  return [
    `# Generated by the FlixelGDX project generator.`,
    `# Documented here: https://flixelgdx.github.io/flixelgdx-website/docs/getting-started`,
    ``,
    `org.gradle.jvmargs=-Xms32m -Xmx512m`,
    `org.gradle.daemon=true`,
    `org.gradle.parallel=true`,
    `org.gradle.caching=true`,
    ``,
    `# FlixelGDX framework version (resolved through JitPack).`,
    `flixelVersion=${o.flixelVersion}`,
    `gameName=${o.gameName}`,
    `gameId=${o.gameId}`,
    ``,
  ].join('\n');
}

/* -------------------------- settings.gradle ------------------------------- */
function settingsGradle(o: GeneratorOptions): string {
  const subs = ['core'];
  if (o.platforms.includes('desktop')) subs.push('lwjgl3');
  if (o.platforms.includes('web')) subs.push('teavm');
  // Android & iOS modules are scaffolded only when selected.
  if (o.platforms.includes('android')) subs.push('android');
  if (o.platforms.includes('ios')) subs.push('ios');
  return [
    `rootProject.name = "${o.gameId}"`,
    ...subs.map((s) => `include "${s}"`),
    ``,
  ].join('\n');
}

/* -------------------------- root build.gradle ----------------------------- */
function rootBuildGradle(o: GeneratorOptions): string {
  const kotlinBlock =
    o.language === 'kotlin'
      ? `\n        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.24"\n`
      : ``;
  const userGradle = o.expert && o.gradleConfig.trim()
    ? `\n/* ----------- expert mode: custom gradle config ----------- */\n${o.gradleConfig}\n`
    : '';
  return [
    `/*`,
    ` * Root build script generated by the FlixelGDX project generator.`,
    ` * - Java ${o.javaVersion}+ (FlixelGDX requires 17 at minimum).`,
    ` * - Pulls the framework from JitPack (no local install needed).`,
    ` */`,
    `buildscript {`,
    `    repositories {`,
    `        mavenCentral()`,
    `        gradlePluginPortal()`,
    `        maven { url 'https://jitpack.io' }`,
    `    }`,
    `    dependencies {${kotlinBlock}    }`,
    `}`,
    ``,
    `allprojects {`,
    `    version = "0.0.1"`,
    `    group = "${o.packageName}"`,
    `    repositories {`,
    `        mavenCentral()`,
    `        google()`,
    `        maven { url 'https://jitpack.io' }`,
    `    }`,
    `}`,
    userGradle,
    ``,
  ].join('\n');
}

/* -------------------------- core build.gradle ----------------------------- */
function coreBuildGradle(o: GeneratorOptions): string {
  const langPlugin =
    o.language === 'java'
      ? `id 'java-library'`
      : o.language === 'groovy'
        ? `id 'groovy'\n    id 'java-library'`
        : `id 'org.jetbrains.kotlin.jvm'\n    id 'java-library'`;

  const langDep =
    o.language === 'groovy'
      ? `\n    implementation "org.codehaus.groovy:groovy-all:3.0.21"`
      : o.language === 'kotlin'
        ? `\n    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.24"`
        : ``;

  return [
    `plugins {`,
    `    ${langPlugin}`,
    `}`,
    ``,
    `java {`,
    `    sourceCompatibility = JavaVersion.VERSION_${o.javaVersion}`,
    `    targetCompatibility = JavaVersion.VERSION_${o.javaVersion}`,
    `}`,
    ``,
    `dependencies {`,
    `    api "com.github.flixelgdx.flixelgdx:flixelgdx-core:\${flixelVersion}"${langDep}`,
    `}`,
    ``,
  ].join('\n');
}

/* -------------------------- lwjgl3 build.gradle --------------------------- */
function lwjgl3BuildGradle(o: GeneratorOptions): string {
  const langPlugin =
    o.language === 'kotlin'
      ? `id 'org.jetbrains.kotlin.jvm'\n    id 'application'`
      : o.language === 'groovy'
        ? `id 'groovy'\n    id 'application'`
        : `id 'application'`;
  const mainSuffix =
    o.language === 'kotlin' ? 'Kt' : '';
  const baseFlags = `-Xms${Math.max(8, Math.floor(o.heapMb / 2))}m -Xmx${o.heapMb}m`;
  const userFlags = o.expert && o.jvmFlags.trim() ? ` ${o.jvmFlags.trim()}` : '';
  return [
    `plugins {`,
    `    ${langPlugin}`,
    `}`,
    ``,
    `application {`,
    `    mainClass = "${o.packageName}.lwjgl3.${o.gameName.replace(/\\s+/g, '')}Lwjgl3Launcher${mainSuffix}"`,
    `    applicationDefaultJvmArgs = ["${baseFlags}${userFlags}".split(" ").findAll { !it.isEmpty() }]`,
    `}`,
    ``,
    `dependencies {`,
    `    implementation project(":core")`,
    `    implementation "com.github.flixelgdx.flixelgdx:flixelgdx-lwjgl3:\${flixelVersion}"`,
    `}`,
    ``,
  ].join('\n');
}

/* -------------------------- teavm build.gradle ---------------------------- */
function teavmBuildGradle(o: GeneratorOptions): string {
  return [
    `plugins {`,
    `    id 'java-library'`,
    `    id 'me.stringdotjar.flixelgdx.teavm' version "\${flixelVersion}"`,
    `}`,
    ``,
    `dependencies {`,
    `    implementation project(":core")`,
    `    implementation "com.github.flixelgdx.flixelgdx:flixelgdx-teavm:\${flixelVersion}"`,
    `}`,
    ``,
  ].join('\n');
}

/* ---------------------- core: game/state source files --------------------- */
function gameClassFiles(o: GeneratorOptions): Record<string, string> {
  const cls = o.gameName.replace(/\s+/g, '');
  const stateCls =
    o.template === 'platformer' ? 'PlatformerState' : 'PlayState';
  const pkg = o.packageName.replace(/[^A-Za-z0-9_.]/g, '_');
  const pkgDir = pkg.replace(/\./g, '/');
  const out: Record<string, string> = {};

  if (o.language === 'java') {
    out[`core/src/main/java/${pkgDir}/${cls}.java`] = [
      `package ${pkg};`,
      ``,
      `import me.stringdotjar.flixelgdx.Flixel;`,
      `import me.stringdotjar.flixelgdx.FlixelGame;`,
      ``,
      `public class ${cls} extends FlixelGame {`,
      `    @Override`,
      `    protected void create() {`,
      `        super.create();`,
      `        Flixel.log.info("${cls} is awake!");`,
      `        Flixel.switchState(new ${stateCls}());`,
      `    }`,
      `}`,
      ``,
    ].join('\n');
    out[`core/src/main/java/${pkgDir}/${stateCls}.java`] = playStateJava(o, stateCls);
  } else if (o.language === 'groovy') {
    out[`core/src/main/groovy/${pkgDir}/${cls}.groovy`] = [
      `package ${pkg}`,
      ``,
      `import me.stringdotjar.flixelgdx.Flixel`,
      `import me.stringdotjar.flixelgdx.FlixelGame`,
      ``,
      `class ${cls} extends FlixelGame {`,
      `    @Override`,
      `    protected void create() {`,
      `        super.create()`,
      `        Flixel.log.info("${cls} is awake!")`,
      `        Flixel.switchState(new ${stateCls}())`,
      `    }`,
      `}`,
      ``,
    ].join(GROOVY_LINE);
    out[`core/src/main/groovy/${pkgDir}/${stateCls}.groovy`] = playStateGroovy(o, stateCls);
  } else {
    out[`core/src/main/kotlin/${pkgDir}/${cls}.kt`] = [
      `package ${pkg}`,
      ``,
      `import me.stringdotjar.flixelgdx.Flixel`,
      `import me.stringdotjar.flixelgdx.FlixelGame`,
      ``,
      `class ${cls} : FlixelGame() {`,
      `    override fun create() {`,
      `        super.create()`,
      `        Flixel.log.info("${cls} is awake!")`,
      `        Flixel.switchState(${stateCls}())`,
      `    }`,
      `}`,
      ``,
    ].join('\n');
    out[`core/src/main/kotlin/${pkgDir}/${stateCls}.kt`] = playStateKotlin(o, stateCls);
  }

  return out;
}

function playStateJava(o: GeneratorOptions, stateCls: string): string {
  const pkg = o.packageName;
  if (o.template === 'platformer') {
    return [
      `package ${pkg};`,
      ``,
      `import me.stringdotjar.flixelgdx.Flixel;`,
      `import me.stringdotjar.flixelgdx.FlixelSprite;`,
      `import me.stringdotjar.flixelgdx.FlixelState;`,
      `import me.stringdotjar.flixelgdx.input.FlixelKeys;`,
      ``,
      `/**`,
      ` * Tiny pre-made platformer scaffold. Replace the placeholder sprite with`,
      ` * something you draw yourself, or load a real spritesheet through`,
      ` * Flixel.assets.`,
      ` */`,
      `public class ${stateCls} extends FlixelState {`,
      `    private FlixelSprite player;`,
      `    private float velocityY = 0f;`,
      ``,
      `    @Override`,
      `    public void create() {`,
      `        super.create();`,
      `        player = new FlixelSprite(40, 80);`,
      `        player.makeGraphic(16, 16, 0xFF2A3CFF);`,
      `        add(player);`,
      `    }`,
      ``,
      `    @Override`,
      `    public void update(float elapsed) {`,
      `        super.update(elapsed);`,
      `        velocityY += 320f * elapsed;`,
      `        if (Flixel.keys.pressed(FlixelKeys.LEFT))  player.x -= 90f * elapsed;`,
      `        if (Flixel.keys.pressed(FlixelKeys.RIGHT)) player.x += 90f * elapsed;`,
      `        if (Flixel.keys.justPressed(FlixelKeys.SPACE)) velocityY = -160f;`,
      `        player.y += velocityY * elapsed;`,
      `        if (player.y > 200) { player.y = 200; velocityY = 0; }`,
      `    }`,
      `}`,
      ``,
    ].join('\n');
  }
  return [
    `package ${pkg};`,
    ``,
    `import me.stringdotjar.flixelgdx.Flixel;`,
    `import me.stringdotjar.flixelgdx.FlixelState;`,
    ``,
    `/** Empty starter state — open this file and start building! */`,
    `public class ${stateCls} extends FlixelState {`,
    `    @Override`,
    `    public void create() {`,
    `        super.create();`,
    `        Flixel.log.info("${stateCls} is ready.");`,
    `    }`,
    ``,
    `    @Override`,
    `    public void update(float elapsed) {`,
    `        super.update(elapsed);`,
    `    }`,
    `}`,
    ``,
  ].join('\n');
}

function playStateGroovy(o: GeneratorOptions, stateCls: string): string {
  const pkg = o.packageName;
  if (o.template === 'platformer') {
    return [
      `package ${pkg}`,
      ``,
      `import me.stringdotjar.flixelgdx.Flixel`,
      `import me.stringdotjar.flixelgdx.FlixelSprite`,
      `import me.stringdotjar.flixelgdx.FlixelState`,
      `import me.stringdotjar.flixelgdx.input.FlixelKeys`,
      ``,
      `class ${stateCls} extends FlixelState {`,
      `    FlixelSprite player`,
      `    float velocityY = 0f`,
      ``,
      `    @Override`,
      `    void create() {`,
      `        super.create()`,
      `        player = new FlixelSprite(40, 80)`,
      `        player.makeGraphic(16, 16, 0xFF2A3CFF as int)`,
      `        add(player)`,
      `    }`,
      ``,
      `    @Override`,
      `    void update(float elapsed) {`,
      `        super.update(elapsed)`,
      `        velocityY += 320f * elapsed`,
      `        if (Flixel.keys.pressed(FlixelKeys.LEFT))  player.x -= 90f * elapsed`,
      `        if (Flixel.keys.pressed(FlixelKeys.RIGHT)) player.x += 90f * elapsed`,
      `        if (Flixel.keys.justPressed(FlixelKeys.SPACE)) velocityY = -160f`,
      `        player.y += velocityY * elapsed`,
      `        if (player.y > 200) { player.y = 200; velocityY = 0 }`,
      `    }`,
      `}`,
      ``,
    ].join('\n');
  }
  return [
    `package ${pkg}`,
    ``,
    `import me.stringdotjar.flixelgdx.Flixel`,
    `import me.stringdotjar.flixelgdx.FlixelState`,
    ``,
    `class ${stateCls} extends FlixelState {`,
    `    @Override`,
    `    void create() {`,
    `        super.create()`,
    `        Flixel.log.info("${stateCls} is ready.")`,
    `    }`,
    ``,
    `    @Override`,
    `    void update(float elapsed) {`,
    `        super.update(elapsed)`,
    `    }`,
    `}`,
    ``,
  ].join('\n');
}

function playStateKotlin(o: GeneratorOptions, stateCls: string): string {
  const pkg = o.packageName;
  if (o.template === 'platformer') {
    return [
      `package ${pkg}`,
      ``,
      `import me.stringdotjar.flixelgdx.Flixel`,
      `import me.stringdotjar.flixelgdx.FlixelSprite`,
      `import me.stringdotjar.flixelgdx.FlixelState`,
      `import me.stringdotjar.flixelgdx.input.FlixelKeys`,
      ``,
      `class ${stateCls} : FlixelState() {`,
      `    private lateinit var player: FlixelSprite`,
      `    private var velocityY = 0f`,
      ``,
      `    override fun create() {`,
      `        super.create()`,
      `        player = FlixelSprite(40f, 80f).apply { makeGraphic(16, 16, 0xFF2A3CFF.toInt()) }`,
      `        add(player)`,
      `    }`,
      ``,
      `    override fun update(elapsed: Float) {`,
      `        super.update(elapsed)`,
      `        velocityY += 320f * elapsed`,
      `        if (Flixel.keys.pressed(FlixelKeys.LEFT))  player.x -= 90f * elapsed`,
      `        if (Flixel.keys.pressed(FlixelKeys.RIGHT)) player.x += 90f * elapsed`,
      `        if (Flixel.keys.justPressed(FlixelKeys.SPACE)) velocityY = -160f`,
      `        player.y += velocityY * elapsed`,
      `        if (player.y > 200f) { player.y = 200f; velocityY = 0f }`,
      `    }`,
      `}`,
      ``,
    ].join('\n');
  }
  return [
    `package ${pkg}`,
    ``,
    `import me.stringdotjar.flixelgdx.Flixel`,
    `import me.stringdotjar.flixelgdx.FlixelState`,
    ``,
    `class ${stateCls} : FlixelState() {`,
    `    override fun create() {`,
    `        super.create()`,
    `        Flixel.log.info("${stateCls} is ready.")`,
    `    }`,
    ``,
    `    override fun update(elapsed: Float) {`,
    `        super.update(elapsed)`,
    `    }`,
    `}`,
    ``,
  ].join('\n');
}

/* --------------------- lwjgl3 launcher source file ----------------------- */
function lwjgl3Launcher(o: GeneratorOptions): Record<string, string> {
  const cls = o.gameName.replace(/\s+/g, '');
  const pkg = `${o.packageName}.lwjgl3`;
  const pkgDir = pkg.replace(/\./g, '/');
  if (o.language === 'kotlin') {
    return {
      [`lwjgl3/src/main/kotlin/${pkgDir}/${cls}Lwjgl3Launcher.kt`]: [
        `package ${pkg}`,
        ``,
        `import me.stringdotjar.flixelgdx.lwjgl3.FlixelLwjgl3Launcher`,
        `import com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration`,
        `import ${o.packageName}.${cls}`,
        ``,
        `fun main() {`,
        `    val config = Lwjgl3ApplicationConfiguration().apply {`,
        `        setTitle("${o.gameName}")`,
        `        setWindowedMode(640, 480)`,
        `        setForegroundFPS(60)`,
        `    }`,
        `    FlixelLwjgl3Launcher.launch(${cls}(), config)`,
        `}`,
        ``,
      ].join('\n'),
    };
  }
  if (o.language === 'groovy') {
    return {
      [`lwjgl3/src/main/groovy/${pkgDir}/${cls}Lwjgl3Launcher.groovy`]: [
        `package ${pkg}`,
        ``,
        `import me.stringdotjar.flixelgdx.lwjgl3.FlixelLwjgl3Launcher`,
        `import com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration`,
        `import ${o.packageName}.${cls}`,
        ``,
        `class ${cls}Lwjgl3Launcher {`,
        `    static void main(String[] args) {`,
        `        def config = new Lwjgl3ApplicationConfiguration()`,
        `        config.setTitle("${o.gameName}")`,
        `        config.setWindowedMode(640, 480)`,
        `        config.setForegroundFPS(60)`,
        `        FlixelLwjgl3Launcher.launch(new ${cls}(), config)`,
        `    }`,
        `}`,
        ``,
      ].join('\n'),
    };
  }
  return {
    [`lwjgl3/src/main/java/${pkgDir}/${cls}Lwjgl3Launcher.java`]: [
      `package ${pkg};`,
      ``,
      `import me.stringdotjar.flixelgdx.lwjgl3.FlixelLwjgl3Launcher;`,
      `import com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration;`,
      `import ${o.packageName}.${cls};`,
      ``,
      `public final class ${cls}Lwjgl3Launcher {`,
      `    public static void main(String[] args) {`,
      `        Lwjgl3ApplicationConfiguration config = new Lwjgl3ApplicationConfiguration();`,
      `        config.setTitle("${o.gameName}");`,
      `        config.setWindowedMode(640, 480);`,
      `        config.setForegroundFPS(60);`,
      `        FlixelLwjgl3Launcher.launch(new ${cls}(), config);`,
      `    }`,
      `}`,
      ``,
    ].join('\n'),
  };
}

/* ----------------------- IDE-specific dotfiles ---------------------------- */
function ideFiles(o: GeneratorOptions): Record<string, string> {
  const out: Record<string, string> = {};
  if (o.ide === 'idea') {
    out['.idea/.gitignore'] = `*\n!.gitignore\n`;
    out['.idea/runConfigurations/Run_Desktop.xml'] =
      `<component name="ProjectRunConfigurationManager">\n` +
      `  <configuration default="false" name="Run Desktop" type="Application" factoryName="Application">\n` +
      `    <option name="MAIN_CLASS_NAME" value="${o.packageName}.lwjgl3.${o.gameName.replace(/\s+/g, '')}Lwjgl3Launcher" />\n` +
      `    <module name="lwjgl3" />\n` +
      `    <option name="VM_PARAMETERS" value="-Xmx${o.heapMb}m" />\n` +
      `    <method v="2"><option name="Gradle.BeforeRunTask" enabled="true" tasks="classes" /></method>\n` +
      `  </configuration>\n` +
      `</component>\n`;
  } else if (o.ide === 'eclipse') {
    out['.classpath'] =
      `<?xml version="1.0" encoding="UTF-8"?>\n` +
      `<classpath>\n` +
      `  <classpathentry kind="src" path="core/src/main/java"/>\n` +
      `  <classpathentry kind="src" path="lwjgl3/src/main/java"/>\n` +
      `  <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-${o.javaVersion}"/>\n` +
      `  <classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/>\n` +
      `  <classpathentry kind="output" path="bin/default"/>\n` +
      `</classpath>\n`;
    out['.project'] =
      `<?xml version="1.0" encoding="UTF-8"?>\n` +
      `<projectDescription>\n` +
      `  <name>${o.gameId}</name>\n` +
      `  <buildSpec>\n` +
      `    <buildCommand><name>org.eclipse.jdt.core.javabuilder</name></buildCommand>\n` +
      `    <buildCommand><name>org.eclipse.buildship.core.gradleprojectbuilder</name></buildCommand>\n` +
      `  </buildSpec>\n` +
      `  <natures>\n` +
      `    <nature>org.eclipse.jdt.core.javanature</nature>\n` +
      `    <nature>org.eclipse.buildship.core.gradleprojectnature</nature>\n` +
      `  </natures>\n` +
      `</projectDescription>\n`;
  } else if (o.ide === 'vscode') {
    out['.vscode/launch.json'] = JSON.stringify(
      {
        version: '0.2.0',
        configurations: [
          {
            type: 'java',
            name: 'Run Desktop',
            request: 'launch',
            mainClass: `${o.packageName}.lwjgl3.${o.gameName.replace(/\s+/g, '')}Lwjgl3Launcher`,
            projectName: 'lwjgl3',
            vmArgs: `-Xmx${o.heapMb}m`,
          },
        ],
      },
      null,
      2
    );
    out['.vscode/settings.json'] = JSON.stringify(
      {
        'java.configuration.runtimes': [
          {name: `JavaSE-${o.javaVersion}`, default: true},
        ],
      },
      null,
      2
    );
  }
  return out;
}

/* --------------------------- README + gitignore --------------------------- */
function readme(o: GeneratorOptions): string {
  return [
    `# ${o.gameName}`,
    ``,
    `A FlixelGDX game generated by the [FlixelGDX project generator](https://flixelgdx.github.io/flixelgdx-website/docs/getting-started).`,
    ``,
    `## Setup`,
    ``,
    `1. Install **JDK ${o.javaVersion}** or newer (FlixelGDX requires Java 17+).`,
    `2. Generate the Gradle wrapper once (uses your system Gradle):`,
    ``,
    `       gradle wrapper`,
    ``,
    `3. From this folder, run the desktop launcher:`,
    ``,
    `       ./gradlew :lwjgl3:run`,
    ``,
    `## What you get`,
    ``,
    `- **Language:** ${o.language}`,
    `- **Java target:** ${o.javaVersion}`,
    `- **FlixelGDX version:** \`${o.flixelVersion}\` (pulled from JitPack)`,
    `- **Default heap:** ${o.heapMb} MB (FlixelGDX is designed to run happily in tiny heaps)`,
    `- **Platforms:** ${o.platforms.join(', ') || 'desktop'}`,
    `- **Template:** ${o.template}`,
    ``,
    `## Project layout`,
    ``,
    `    core/         — gameplay code (states, sprites, logic)`,
    `    lwjgl3/       — desktop launcher (LWJGL3 / OpenGL)`,
    o.platforms.includes('web') ? `    teavm/        — browser launcher (TeaVM)` : ``,
    ``,
    `## Learn more`,
    ``,
    `- [Your First Project tutorial](https://flixelgdx.github.io/flixelgdx-website/docs/your-first-project)`,
    `- [API reference](https://flixelgdx.github.io/flixelgdx-website/api/)`,
    `- [FlixelGDX on GitHub](https://github.com/flixelgdx/flixelgdx)`,
    ``,
  ]
    .filter(Boolean)
    .join('\n');
}

function gitignore(): string {
  return [
    `.gradle/`,
    `build/`,
    `bin/`,
    `out/`,
    `*.iml`,
    `.idea/workspace.xml`,
    `.idea/tasks.xml`,
    `.idea/caches/`,
    `.idea/libraries/`,
    `.DS_Store`,
    `*.log`,
    ``,
  ].join('\n');
}

/* --------------------------- public entry point --------------------------- */
export function buildProjectFiles(o: GeneratorOptions): Record<string, string> {
  const files: Record<string, string> = {};
  files['README.md'] = readme(o);
  files['.gitignore'] = gitignore();
  files['settings.gradle'] = settingsGradle(o);
  files['build.gradle'] = rootBuildGradle(o);
  files['gradle.properties'] = gradleProperties(o);
  files['core/build.gradle'] = coreBuildGradle(o);
  Object.assign(files, gameClassFiles(o));
  if (o.platforms.includes('desktop')) {
    files['lwjgl3/build.gradle'] = lwjgl3BuildGradle(o);
    Object.assign(files, lwjgl3Launcher(o));
  }
  if (o.platforms.includes('web')) {
    files['teavm/build.gradle'] = teavmBuildGradle(o);
  }
  Object.assign(files, ideFiles(o));
  return files;
}
