import {buildStartupHelperJava} from './startupHelperJava';

/* ----------------------------------------------------------------------------
 * Project template files for the FlixelGDX project generator.
 *
 * Each builder returns a record of `{relativePath: fileContents}` that we feed
 * into JSZip. We intentionally generate textual files (build scripts, Java /
 * Groovy / Kotlin sources, settings.gradle etc) instead of bundling binary
 * Gradle wrapper jars. The Gradle wrapper jar is embedded separately for
 * offline use.
 *
 * JitPack publishes Flixel Gradle plugins under maven coordinates
 * (`com.github.flixelgdx.flixelgdx:flixelgdx-*-plugin`) while the plugin
 * IDs stay `me.stringdotjar.flixelgdx.*` — Gradle needs the
 * `pluginManagement.resolutionStrategy` mapping below so the plugins DSL
 * resolves (otherwise you get “plugin … not found” / apply failures).
 * --------------------------------------------------------------------------- */

/** Pin with framework / COMPILING.md (TeaVM Gradle plugin used by consumers). */
const TEAVM_GRADLE_PLUGIN_VERSION = '0.13.0';
/** Pin with Kotlin stdlib coordinate in generated `core` / `lwjgl3`. */
const KOTLIN_VERSION = '1.9.24';
/** Mirrors README “Add it with JitPack” — consumer-facing group on JitPack. */
const JITPACK_FLIXEL_COORD = 'com.github.flixelgdx.flixelgdx';
/** Matches flixelgdx-lwjgl3 POM (com.badlogicgames.gdx:gdx-backend-lwjgl3). */
const GDX_VERSION = '1.14.0';
/** GraalVM Native Build Tools (Gradle 9 compatible). */
const GRAALVM_NATIVE_PLUGIN_VERSION = '0.10.6';
/** Construo desktop packaging plugin. */
const CONSTRUO_PLUGIN_VERSION = '2.1.0';

export type Language = 'java' | 'groovy' | 'kotlin';
export type Template = 'blank' | 'platformer';
export type Platform = 'desktop' | 'web' | 'android' | 'ios';
export type JdkVendor =
  | 'graalvm'       // GraalVM Community — fast startup, JIT/AOT options
  | 'temurin'       // Eclipse Temurin (Adoptium) — standard Hotspot
  | 'corretto'      // Amazon Corretto — long-term-supported Hotspot
  | 'zulu';         // Azul Zulu — broad version coverage

export interface GeneratorOptions {
  gameName: string;
  gameId: string;
  packageName: string;
  language: Language;
  javaVersion: number;
  flixelVersion: string;
  template: Template;
  platforms: Platform[];
  jdkVendor: JdkVendor;
  expert: boolean;
  heapMb: number;
  jvmFlags: string;
  gradleConfig: string;
}

/**
 * Gradle `JvmVendorSpec` enum value matching a `JdkVendor`. See
 * https://docs.gradle.org/current/javadoc/org/gradle/jvm/toolchain/JvmVendorSpec.html
 */
export function gradleVendorSpec(v: JdkVendor): string {
  switch (v) {
    case 'graalvm': return 'GRAAL_VM';
    case 'temurin': return 'ADOPTIUM';
    case 'corretto': return 'AMAZON';
    case 'zulu': return 'AZUL';
  }
}

/** Safe inside Java / Groovy double-quoted string literals (game window title, logs, etc.). */
function escDoubleQuotedJvm(name: string): string {
  return name
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n');
}

/** Safe inside Kotlin double-quoted strings (also escapes $ so ${...} is not accidentally formed). */
function escDoubleQuotedKotlin(name: string): string {
  return name
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\$/g, '\\$')
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n');
}

/* -------------------------- gradle.properties ----------------------------- */
function gradleProperties(o: GeneratorOptions): string {
  const lines = [
    `# Generated by the FlixelGDX project generator.`,
    `# Documented here: https://flixelgdx.github.io/flixelgdx-website/docs/getting-started`,
    ``,
    `org.gradle.jvmargs=-Xms32m -Xmx512m`,
    `org.gradle.daemon=true`,
    `org.gradle.parallel=true`,
    `org.gradle.caching=true`,
    `org.gradle.configuration-cache=true`,
    `org.gradle.vfs.watch=true`,
    ``,
    `# UTF-8 for Gradle and JVM processes on every OS.`,
    `systemProp.file.encoding=UTF-8`,
    ``,
    `# FlixelGDX framework version (resolved through JitPack).`,
    `flixelVersion=${o.flixelVersion}`,
    `# libGDX LWJGL3 backend version (Lwjgl3NativesLoader and natives align with FlixelGDX).`,
    `gdxVersion=${GDX_VERSION}`,
    `gameName=${o.gameName}`,
    `gameId=${o.gameId}`,
    ``,
    `# GraalVM Native Image (nativeCompile, nativeRun, etc.). Set to true only when you use a GraalVM-capable JDK and want native binaries.`,
    `enableGraalNative=false`,
    ``,
  ];
  if (o.platforms.includes('web')) {
    lines.push(
      `# Reflection metadata scope for TeaVM (see COMPILING.md in flixelgdx/flixelgdx).`,
      `flixelReflectionProfile=STANDARD`,
      ``
    );
  }
  return lines.join('\n');
}

/* -------------------------- settings.gradle ------------------------------- */
function settingsGradle(o: GeneratorOptions): string {
  const subs = ['core'];
  if (o.platforms.includes('desktop')) subs.push('lwjgl3');
  if (o.platforms.includes('web')) subs.push('teavm');
  if (o.platforms.includes('android')) subs.push('android');
  if (o.platforms.includes('ios')) subs.push('ios');
  return [
    `// Plugin versions + repositories. JitPack hosts Flixel Gradle plugins`,
    `// under maven coordinates (${JITPACK_FLIXEL_COORD}:flixelgdx-*-plugin).`,
    `// Plugin IDs are still me.stringdotjar.flixelgdx.*. Without the mapping`,
    `// below, Gradle fails to resolve the plugin marker from the portal.`,
    `pluginManagement {`,
    `  plugins {`,
    `    id 'org.jetbrains.kotlin.jvm' version '${KOTLIN_VERSION}'`,
    `    id 'org.teavm' version '${TEAVM_GRADLE_PLUGIN_VERSION}'`,
    `    id 'org.graalvm.buildtools.native' version '${GRAALVM_NATIVE_PLUGIN_VERSION}'`,
    `    id 'io.github.fourlastor.construo' version '${CONSTRUO_PLUGIN_VERSION}'`,
    `    id 'me.stringdotjar.flixelgdx.logging' version '${o.flixelVersion}'`,
    `  }`,
    `  repositories {`,
    `    mavenLocal()`,
    `    maven { url 'https://jitpack.io' }`,
    `    gradlePluginPortal()`,
    `  }`,
    `  resolutionStrategy {`,
    `    eachPlugin {`,
    `      def jitpackArtifact = [`,
    `        'me.stringdotjar.flixelgdx.teavm': 'flixelgdx-teavm-plugin',`,
    `        'me.stringdotjar.flixelgdx.logging': 'flixelgdx-logging-plugin',`,
    `      ][requested.id.id]`,
    `      if (jitpackArtifact != null) {`,
    `        useModule('${JITPACK_FLIXEL_COORD}:' + jitpackArtifact + ':' + requested.version.toString())`,
    `      }`,
    `    }`,
    `  }`,
    `}`,
    ``,
    `// Auto-provision the selected JDK at build time.`,
    `// The Foojay Toolchains Resolver lets Gradle download a matching JDK on`,
    `// demand, so users only need a JDK to *bootstrap* Gradle itself.`,
    `plugins {`,
    `  id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'`,
    `}`,
    ``,
    `rootProject.name = "${o.gameId}"`,
    ...subs.map((s) => `include "${s}"`),
    ``,
  ].join('\n');
}

/* -------------------------- root build.gradle ----------------------------- */
function rootBuildGradle(o: GeneratorOptions): string {
  const userGradle = o.expert && o.gradleConfig.trim()
    ? `\n/* ----------- expert mode: custom gradle config ----------- */\n${o.gradleConfig}\n`
    : '';
  return [
    `/*`,
    ` * Root build script generated by the FlixelGDX project generator.`,
    ` * - Java ${o.javaVersion}+ (FlixelGDX requires 17 at minimum).`,
    ` * - Pulls the framework from JitPack (no local install needed).`,
    ` * - Kotlin plugin versions live in pluginManagement {} in settings.gradle.`,
    ` */`,
    `allprojects {`,
    `  version = "0.0.1"`,
    `  group = "${o.packageName}"`,
    `  repositories {`,
    `    mavenCentral()`,
    `    google()`,
    `    maven { url 'https://jitpack.io' }`,
    `  }`,
    `}`,
    userGradle,
    ``,
  ].join('\n');
}

/* -------------------------- core build.gradle ----------------------------- */
function coreBuildGradle(o: GeneratorOptions): string {
  const langPlugin =
    o.language === 'java'
      ? `id 'java-library'\n  id 'me.stringdotjar.flixelgdx.logging'`
      : o.language === 'groovy'
        ? `id 'groovy'\n  id 'java-library'\n  id 'me.stringdotjar.flixelgdx.logging'`
        : `id 'org.jetbrains.kotlin.jvm'\n  id 'java-library'\n  id 'me.stringdotjar.flixelgdx.logging'`;

  const langDep =
    o.language === 'groovy'
      ? `\n  implementation "org.codehaus.groovy:groovy-all:3.0.21"`
      : o.language === 'kotlin'
        ? `\n  implementation "org.jetbrains.kotlin:kotlin-stdlib:${KOTLIN_VERSION}"`
        : ``;

  return [
    `plugins {`,
    `  ${langPlugin}`,
    `}`,
    ``,
    `java {`,
    `  // Gradle will auto-download a matching JDK from the configured vendor.`,
    `  toolchain {`,
    `    languageVersion = JavaLanguageVersion.of(${o.javaVersion})`,
    `    vendor = JvmVendorSpec.${gradleVendorSpec(o.jdkVendor)}`,
    `  }`,
    `  sourceCompatibility = JavaVersion.VERSION_${o.javaVersion}`,
    `  targetCompatibility = JavaVersion.VERSION_${o.javaVersion}`,
    `}`,
    ``,
    `dependencies {`,
    `  api "${JITPACK_FLIXEL_COORD}:flixelgdx-core:\${flixelVersion}"${langDep}`,
    `}`,
    ``,
  ].join('\n');
}

/* ------------------------ nativeimage.gradle (desktop) -------------------- */
/**
 * Loaded from {@code lwjgl3/build.gradle} when {@code enableGraalNative} is true.
 * Applies GraalVM Native Build Tools configuration in the lwjgl3 subproject context
 * so plugin resolution uses {@code settings.gradle} pluginManagement.
 */
function nativeImageGradle(): string {
  return [
    `// GraalVM Native Image (only loaded when enableGraalNative=true in gradle.properties).`,
    `// Resource patterns are adapted from https://lyze.dev/2021/04/29/libGDX-Internal-Assets-List/`,
    ``,
    `import groovy.json.JsonOutput`,
    `import java.util.Locale`,
    ``,
    `ext.appName = rootProject.findProperty('gameId') ?: rootProject.name`,
    ``,
    `def isMacOsNative = System.getProperty('os.name', '').toLowerCase(Locale.ROOT).contains('mac')`,
    ``,
    `graalvmNative {`,
    `  toolchainDetection = true`,
    `  binaries {`,
    `    main {`,
    `      imageName = appName`,
    `      mainClass = application.mainClass`,
    `      requiredVersion = '23.0'`,
    `      buildArgs.add('-march=compatibility')`,
    `      buildArgs.add('-H:+ReportExceptionStackTraces')`,
    `      if (isMacOsNative) {`,
    `        buildArgs.add('-J-XstartOnFirstThread')`,
    `      }`,
    `      jvmArgs.addAll('-Dfile.encoding=UTF8')`,
    `      sharedLibrary = false`,
    `      resources {`,
    `        autodetect()`,
    `      }`,
    `    }`,
    `  }`,
    `}`,
    ``,
    `tasks.named('run').configure {`,
    `  doNotTrackState('Running the app should not be affected by Graal.')`,
    `}`,
    ``,
    `afterEvaluate {`,
    `  tasks.matching { it.name == 'generateResourcesConfigFile' }.configureEach { gen ->`,
    `    gen.doFirst {`,
    `      def assetsFolder = rootProject.file('assets')`,
    `      def resFolder = file('src/main/resources/META-INF/native-image/' + ext.appName)`,
    `      resFolder.mkdirs()`,
    `      def resFile = new File(resFolder, 'resource-config.json')`,
    `      resFile.delete()`,
    ``,
    `      def namePatterns = []`,
    `      if (assetsFolder.exists()) {`,
    `        fileTree(assetsFolder).each { namePatterns << java.util.regex.Pattern.quote(it.name) }`,
    `      }`,
    `      def middle = namePatterns.isEmpty() ? '' : namePatterns.join('|') + '|'`,
    `      def pattern = '.*(' + middle + 'libgdx.+\\\\.png|lsans.+)'`,
    ``,
    `      def model = [`,
    `        resources: [includes: [[pattern: pattern]]],`,
    `        bundles: []`,
    `      ]`,
    `      resFile.text = JsonOutput.prettyPrint(JsonOutput.toJson(model))`,
    `    }`,
    `  }`,
    `}`,
    ``,
  ].join('\n');
}

/* -------------------------- lwjgl3 build.gradle --------------------------- */
function lwjgl3BuildGradle(o: GeneratorOptions): string {
  const cls = o.gameName.replace(/\s+/g, '');
  const mainSuffix = o.language === 'kotlin' ? 'Kt' : '';
  const mainClassVal = `${o.packageName}.lwjgl3.${cls}Lwjgl3Launcher${mainSuffix}`;
  const langPlugin =
    o.language === 'kotlin'
      ? `id 'org.jetbrains.kotlin.jvm'\n  id 'application'\n  id 'io.github.fourlastor.construo'`
      : o.language === 'groovy'
        ? `id 'groovy'\n  id 'application'\n  id 'io.github.fourlastor.construo'`
        : `id 'application'\n  id 'io.github.fourlastor.construo'`;
  const baseFlags = `-Xms${Math.max(8, Math.floor(o.heapMb / 2))}m -Xmx${o.heapMb}m`;
  const userFlags = o.expert && o.jvmFlags.trim() ? ` ${o.jvmFlags.trim()}` : '';
  return [
    `import io.github.fourlastor.construo.Target`,
    `import java.util.Locale`,
    ``,
    `plugins {`,
    `  ${langPlugin}`,
    `}`,
    ``,
    `java {`,
    `  toolchain {`,
    `    languageVersion = JavaLanguageVersion.of(${o.javaVersion})`,
    `    vendor = JvmVendorSpec.${gradleVendorSpec(o.jdkVendor)}`,
    `  }`,
    `}`,
    ``,
    `def isMacOs = System.getProperty('os.name', '').toLowerCase(Locale.ROOT).contains('mac')`,
    ``,
    `application {`,
    `  mainClass = "${mainClassVal}"`,
    `  // tokenize() splits on whitespace so each JVM flag is its own list entry (no accidental nested lists).`,
    `  def baseJvmArgs = "${baseFlags}${userFlags}".tokenize()`,
    `  // GLFW on macOS expects the JVM main thread; this matches LibGDX StartupHelper guidance.`,
    `  applicationDefaultJvmArgs = baseJvmArgs + (isMacOs ? ['-XstartOnFirstThread'] : [])`,
    `}`,
    ``,
    `dependencies {`,
    `  implementation project(":core")`,
    `  implementation "${JITPACK_FLIXEL_COORD}:flixelgdx-lwjgl3:\${flixelVersion}"`,
    `  // Lwjgl3NativesLoader and other backend classes used by the vendored StartupHelper.java in this module.`,
    `  implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:\${gdxVersion}"`,
    `}`,
    ``,
    `construo {`,
    `  name.set(providers.gradleProperty("gameId"))`,
    `  humanName.set(providers.gradleProperty("gameName"))`,
    `  mainClass.set(application.mainClass.get())`,
    `  outputDir.set(rootProject.layout.projectDirectory.dir("dist"))`,
    `  roast {`,
    `    runOnFirstThread.set(true)`,
    `  }`,
    `  targets.configure {`,
    `    create("linuxX64", Target.Linux) {`,
    `      architecture.set(Target.Architecture.X86_64)`,
    `      jdkUrl.set("https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.13%2B11/OpenJDK17U-jdk_x64_linux_hotspot_17.0.13_11.tar.gz")`,
    `    }`,
    `    create("macOsAarch64", Target.MacOs) {`,
    `      architecture.set(Target.Architecture.AARCH64)`,
    `      jdkUrl.set("https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.13%2B11/OpenJDK17U-jdk_aarch64_mac_hotspot_17.0.13_11.tar.gz")`,
    `      identifier.set("${o.packageName}.desktop")`,
    `      def v = providers.gradleProperty("version").orElse("0.0.1").get()`,
    `      buildNumber.set(v)`,
    `      versionNumber.set(v)`,
    `    }`,
    `    create("winX64", Target.Windows) {`,
    `      architecture.set(Target.Architecture.X86_64)`,
    `      jdkUrl.set("https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.13%2B11/OpenJDK17U-jdk_x64_windows_hotspot_17.0.13_11.zip")`,
    `    }`,
    `  }`,
    `}`,
    ``,
    `tasks.register('runnableJar', Jar) {`,
    `  group = 'distribution'`,
    `  description = 'Fat runnable game JAR with dependencies and assets (run with: java -jar ...).'`,
    `  dependsOn tasks.classes`,
    `  duplicatesStrategy = DuplicatesStrategy.EXCLUDE`,
    `  archiveFileName = '${o.gameId}-runnable.jar'`,
    `  destinationDirectory = rootProject.layout.buildDirectory.dir('pack')`,
    `  manifest {`,
    `    attributes('Main-Class': application.mainClass.get())`,
    `  }`,
    `  from sourceSets.main.output`,
    `  from {`,
    `    configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }`,
    `  } {`,
    `    exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA', 'META-INF/DEPENDENCIES', 'META-INF/LICENSE*', 'META-INF/NOTICE*', 'module-info.class'`,
    `  }`,
    `  from(rootProject.layout.projectDirectory.dir('assets')) {`,
    `    into 'assets'`,
    `  }`,
    `}`,
    ``,
    `if (Boolean.valueOf((findProperty('enableGraalNative') ?: 'false').toString())) {`,
    `  apply plugin: 'org.graalvm.buildtools.native'`,
    `  apply from: 'nativeimage.gradle'`,
    `}`,
    ``,
  ].join('\n');
}

/* -------------------------- teavm build.gradle ---------------------------- */
function teavmBuildGradle(o: GeneratorOptions): string {
  const cls = o.gameName.replace(/\s+/g, '');
  const mainFqcn =
    o.language === 'kotlin'
      ? `${o.packageName}.teavm.${cls}TeaVMLauncherKt`
      : `${o.packageName}.teavm.${cls}TeaVMLauncher`;

  const langPlugins =
    o.language === 'kotlin'
      ? `id 'org.jetbrains.kotlin.jvm'\n  id 'java-library'`
      : o.language === 'groovy'
        ? `id 'groovy'\n  id 'java-library'`
        : `id 'java-library'`;

  const langDep =
    o.language === 'groovy'
      ? `\n  implementation "org.codehaus.groovy:groovy-all:3.0.21"`
      : o.language === 'kotlin'
        ? `\n  implementation "org.jetbrains.kotlin:kotlin-stdlib:${KOTLIN_VERSION}"`
        : ``;

  const jsBundle = `${o.gameId.replace(/[^a-z0-9_-]/gi, '-')}.js`;

  return [
    `plugins {`,
    `  ${langPlugins}`,
    `  // Must be applied beside me.stringdotjar.flixelgdx.teavm (see COMPILING.md in flixelgdx).`,
    `  id 'org.teavm'`,
    `  id 'me.stringdotjar.flixelgdx.teavm' version "\${flixelVersion}"`,
    `}`,
    ``,
    `java {`,
    `  toolchain {`,
    `    languageVersion = JavaLanguageVersion.of(${o.javaVersion})`,
    `    vendor = JvmVendorSpec.${gradleVendorSpec(o.jdkVendor)}`,
    `  }`,
    `}`,
    ``,
    `teavm {`,
    `  all {`,
    `    mainClass = "${mainFqcn}"`,
    `  }`,
    `  js {`,
    `    addedToWebApp = true`,
    `    targetFileName = "${jsBundle}"`,
    `  }`,
    `}`,
    ``,
    `dependencies {`,
    `  implementation project(":core")`,
    `  implementation "${JITPACK_FLIXEL_COORD}:flixelgdx-teavm:\${flixelVersion}"${langDep}`,
    `}`,
    ``,
  ].join('\n');
}

/* --------------------- teavm launcher source file ----------------------- */
function teavmLauncher(o: GeneratorOptions): Record<string, string> {
  const cls = o.gameName.replace(/\s+/g, '');
  const gameCls = `${cls}Game`;
  const pkg = `${o.packageName}.teavm`;
  const pkgDir = pkg.replace(/\./g, '/');

  if (o.language === 'kotlin') {
    return {
      [`teavm/src/main/kotlin/${pkgDir}/${cls}TeaVMLauncher.kt`]: [
        `package ${pkg}`,
        ``,
        `import me.stringdotjar.flixelgdx.backend.teavm.FlixelTeaVMLauncher`,
        `import ${o.packageName}.${gameCls}`,
        ``,
        `/**`,
        ` * Browser entry point.`,
        ` * <p>`,
        ` * TeaVM turns your JVM bytecode into JavaScript.`,
        ` * <p>`,
        ` * FlixelTeaVMLauncher connects that web runtime to your FlixelGame.`,
        ` */`,
        `fun main() {`,
        `  FlixelTeaVMLauncher.launch(${gameCls}())`,
        `}`,
        ``,
      ].join('\n'),
    };
  }
  if (o.language === 'groovy') {
    return {
      [`teavm/src/main/groovy/${pkgDir}/${cls}TeaVMLauncher.groovy`]: [
        `package ${pkg}`,
        ``,
        `import me.stringdotjar.flixelgdx.backend.teavm.FlixelTeaVMLauncher`,
        `import ${o.packageName}.${gameCls}`,
        ``,
        `/**`,
        ` * Browser entry point.`,
        ` * <p>`,
        ` * TeaVM turns your JVM bytecode into JavaScript.`,
        ` * <p>`,
        ` * FlixelTeaVMLauncher connects that web runtime to your FlixelGame.`,
        ` */`,
        `final class ${cls}TeaVMLauncher {`,
        ``,
        `  static void main(String[] args) {`,
        `    FlixelTeaVMLauncher.launch(new ${gameCls}())`,
        `  }`,
        ``,
        `  private ${cls}TeaVMLauncher() {}`,
        `}`,
        ``,
      ].join('\n'),
    };
  }
  return {
    [`teavm/src/main/java/${pkgDir}/${cls}TeaVMLauncher.java`]: [
      `package ${pkg};`,
      ``,
      `import me.stringdotjar.flixelgdx.backend.teavm.FlixelTeaVMLauncher;`,
      `import ${o.packageName}.${gameCls};`,
      ``,
      `/**`,
      ` * Browser entry point.`,
      ` * <p>`,
      ` * TeaVM turns your JVM bytecode into JavaScript.`,
      ` * <p>`,
      ` * FlixelTeaVMLauncher connects that web runtime to your FlixelGame.`,
      ` */`,
      `public final class ${cls}TeaVMLauncher {`,
      ``,
      `  public static void main(String[] args) {`,
      `    FlixelTeaVMLauncher.launch(new ${gameCls}());`,
      `  }`,
      ``,
      `  private ${cls}TeaVMLauncher() {}`,
      `}`,
      ``,
    ].join('\n'),
  };
}

/* ---------------------- core: game/state source files --------------------- */
function gameClassFiles(o: GeneratorOptions): Record<string, string> {
  const cls = o.gameName.replace(/\s+/g, '');
  const gameCls = `${cls}Game`;
  const stateCls =
    o.template === 'platformer' ? 'PlatformerState' : 'PlayState';
  const pkg = o.packageName.replace(/[^A-Za-z0-9_.]/g, '_');
  const pkgDir = pkg.replace(/\./g, '/');
  const jTitle = escDoubleQuotedJvm(o.gameName);
  const kTitle = escDoubleQuotedKotlin(o.gameName);
  const out: Record<string, string> = {};

  if (o.language === 'java') {
    out[`core/src/main/java/${pkgDir}/${gameCls}.java`] = [
      `package ${pkg};`,
      ``,
      `import com.badlogic.gdx.Gdx;`,
      `import me.stringdotjar.flixelgdx.Flixel;`,
      `import me.stringdotjar.flixelgdx.FlixelGame;`,
      ``,
      `/**`,
      ` * Your game entry class.`,
      ` * <p>`,
      ` * FlixelGame owns the window settings and picks the first FlixelState.`,
      ` * <p>`,
      ` * If you are new here, start in ${stateCls}.java. That file is where you spawn sprites,`,
      ` * load sounds, and write your first update loop.`,
      ` */`,
      `public class ${gameCls} extends FlixelGame {`,
      ``,
      `  public ${gameCls}() {`,
      `    super("${jTitle}", 640, 480, new ${stateCls}());`,
      `  }`,
      ``,
      `  @Override`,
      `  public void create() {`,
      `    Gdx.app.setApplicationLogger(Flixel.getLogger());`,
      `    super.create();`,
      `  }`,
      `}`,
      ``,
    ].join('\n');
    out[`core/src/main/java/${pkgDir}/${stateCls}.java`] = playStateJava(o, stateCls);
  } else if (o.language === 'groovy') {
    out[`core/src/main/groovy/${pkgDir}/${gameCls}.groovy`] = [
      `package ${pkg}`,
      ``,
      `import com.badlogic.gdx.Gdx`,
      `import me.stringdotjar.flixelgdx.Flixel`,
      `import me.stringdotjar.flixelgdx.FlixelGame`,
      ``,
      `/**`,
      ` * Your game entry class.`,
      ` * <p>`,
      ` * FlixelGame owns the window settings and picks the first FlixelState.`,
      ` * <p>`,
      ` * If you are new here, start in ${stateCls}.groovy. That file is where you spawn sprites,`,
      ` * load sounds, and write your first update loop.`,
      ` */`,
      `class ${gameCls} extends FlixelGame {`,
      ``,
      `  ${gameCls}() {`,
      `    super("${jTitle}", 640, 480, new ${stateCls}())`,
      `  }`,
      ``,
      `  @Override`,
      `  void create() {`,
      `    Gdx.app.setApplicationLogger(Flixel.getLogger())`,
      `    super.create()`,
      `  }`,
      `}`,
      ``,
    ].join('\n');
    out[`core/src/main/groovy/${pkgDir}/${stateCls}.groovy`] = playStateGroovy(o, stateCls);
  } else {
    out[`core/src/main/kotlin/${pkgDir}/${gameCls}.kt`] = [
      `package ${pkg}`,
      ``,
      `import com.badlogic.gdx.Gdx`,
      `import me.stringdotjar.flixelgdx.Flixel`,
      `import me.stringdotjar.flixelgdx.FlixelGame`,
      ``,
      `/**`,
      ` * Your game entry class.`,
      ` * <p>`,
      ` * FlixelGame owns the window settings and picks the first FlixelState.`,
      ` * <p>`,
      ` * If you are new here, start in ${stateCls}.kt. That file is where you spawn sprites,`,
      ` * load sounds, and write your first update loop.`,
      ` */`,
      `open class ${gameCls} : FlixelGame("${kTitle}", 640, 480, ${stateCls}()) {`,
      ``,
      `  override fun create() {`,
      `    Gdx.app.setApplicationLogger(Flixel.getLogger())`,
      `    super.create()`,
      `  }`,
      `}`,
      ``,
    ].join('\n');
    out[`core/src/main/kotlin/${pkgDir}/${stateCls}.kt`] = playStateKotlin(o, stateCls);
  }

  return out;
}

function playStateJava(o: GeneratorOptions, stateCls: string): string {
  const pkg = o.packageName;
  if (o.template === 'platformer') {
    return [
      `package ${pkg};`,
      ``,
      `import com.badlogic.gdx.graphics.Color;`,
      `import me.stringdotjar.flixelgdx.Flixel;`,
      `import me.stringdotjar.flixelgdx.FlixelSprite;`,
      `import me.stringdotjar.flixelgdx.FlixelState;`,
      `import me.stringdotjar.flixelgdx.input.keyboard.FlixelKey;`,
      ``,
      `/**`,
      ` * Tiny starter level with a controllable block.`,
      ` * <p>`,
      ` * Read this like a mini tutorial:`,
      ` * <p>`,
      ` * create() runs once when this state becomes active. Build your scene there.`,
      ` * <p>`,
      ` * update(elapsed) runs every frame. elapsed is seconds since the last frame (use it for smooth motion).`,
      ` * <p>`,
      ` * FlixelSprite is a simple game object with a position (x, y) you can draw.`,
      ` * <p>`,
      ` * makeGraphic builds a solid rectangle so you can run the project before you add art.`,
      ` * <p>`,
      ` * Next experiments: change the color in new Color(0xFF2A3CFF), resize the sprite, or print logs with`,
      ` * Flixel.info("hello").`,
      ` */`,
      `public class ${stateCls} extends FlixelState {`,
      ``,
      `  private FlixelSprite player;`,
      `  private float velocityY;`,
      ``,
      `  @Override`,
      `  public void create() {`,
      `    super.create();`,
      `    player = new FlixelSprite(40f, 80f);`,
      `    player.makeGraphic(16, 16, new Color(0xFF2A3CFF));`,
      `    add(player);`,
      `    Flixel.info("PlatformerState is running. Use arrow keys and space to move and jump.");`,
      `  }`,
      ``,
      `  @Override`,
      `  public void update(float elapsed) {`,
      `    super.update(elapsed);`,
      `    velocityY += 320f * elapsed;`,
      `    if (Flixel.keys.pressed(FlixelKey.LEFT)) {`,
      `      player.x -= 90f * elapsed;`,
      `    }`,
      `    if (Flixel.keys.pressed(FlixelKey.RIGHT)) {`,
      `      player.x += 90f * elapsed;`,
      `    }`,
      `    if (Flixel.keys.justPressed(FlixelKey.SPACE)) {`,
      `      velocityY = -160f;`,
      `    }`,
      `    player.y += velocityY * elapsed;`,
      `    if (player.y > 200f) {`,
      `      player.y = 200f;`,
      `      velocityY = 0f;`,
      `    }`,
      `  }`,
      `}`,
      ``,
    ].join('\n');
  }
  return [
    `package ${pkg};`,
    ``,
    `import me.stringdotjar.flixelgdx.Flixel;`,
    `import me.stringdotjar.flixelgdx.FlixelState;`,
    ``,
    `/**`,
    ` * Your first FlixelState (think of it as one "screen" of your game).`,
    ` * <p>`,
    ` * What to try first:`,
    ` * <p>`,
    ` * Put setup code in create(). It runs once when this state starts.`,
    ` * <p>`,
    ` * Put movement and rules in update(elapsed). It runs every frame.`,
    ` * <p>`,
    ` * When you want a new screen, create another FlixelState subclass and call`,
    ` * Flixel.switchState(new MyOtherState()) from anywhere after Flixel has started.`,
    ` */`,
    `public class ${stateCls} extends FlixelState {`,
    ``,
    `  @Override`,
    `  public void create() {`,
    `    super.create();`,
    `    Flixel.info("${stateCls} is ready. Add a FlixelSprite here when you want something on screen.");`,
    `  }`,
    ``,
    `  @Override`,
    `  public void update(float elapsed) {`,
    `    super.update(elapsed);`,
    `  }`,
    `}`,
    ``,
  ].join('\n');
}

function playStateGroovy(o: GeneratorOptions, stateCls: string): string {
  const pkg = o.packageName;
  if (o.template === 'platformer') {
    return [
      `package ${pkg}`,
      ``,
      `import com.badlogic.gdx.graphics.Color`,
      `import me.stringdotjar.flixelgdx.Flixel`,
      `import me.stringdotjar.flixelgdx.FlixelSprite`,
      `import me.stringdotjar.flixelgdx.FlixelState`,
      `import me.stringdotjar.flixelgdx.input.keyboard.FlixelKey`,
      ``,
      `/**`,
      ` * Tiny starter level with a controllable block.`,
      ` * <p>`,
      ` * Read this like a mini tutorial:`,
      ` * <p>`,
      ` * create() runs once when this state becomes active. Build your scene there.`,
      ` * <p>`,
      ` * update(elapsed) runs every frame. elapsed is seconds since the last frame (use it for smooth motion).`,
      ` * <p>`,
      ` * FlixelSprite is a simple game object with a position (x, y) you can draw.`,
      ` * <p>`,
      ` * makeGraphic builds a solid rectangle so you can run the project before you add art.`,
      ` * <p>`,
      ` * Next experiments: change the color in new Color(0xFF2A3CFF), resize the sprite, or print logs with`,
      ` * Flixel.info("hello").`,
      ` */`,
      `class ${stateCls} extends FlixelState {`,
      ``,
      `  FlixelSprite player`,
      `  float velocityY = 0f`,
      ``,
      `  @Override`,
      `  void create() {`,
      `    super.create()`,
      `    player = new FlixelSprite(40f, 80f)`,
      `    player.makeGraphic(16, 16, new Color(0xFF2A3CFF))`,
      `    add(player)`,
      `    Flixel.info("PlatformerState is running. Use arrow keys and space to move and jump.")`,
      `  }`,
      ``,
      `  @Override`,
      `  void update(float elapsed) {`,
      `    super.update(elapsed)`,
      `    velocityY += 320f * elapsed`,
      `    if (Flixel.keys.pressed(FlixelKey.LEFT)) {`,
      `      player.x -= 90f * elapsed`,
      `    }`,
      `    if (Flixel.keys.pressed(FlixelKey.RIGHT)) {`,
      `      player.x += 90f * elapsed`,
      `    }`,
      `    if (Flixel.keys.justPressed(FlixelKey.SPACE)) {`,
      `      velocityY = -160f`,
      `    }`,
      `    player.y += velocityY * elapsed`,
      `    if (player.y > 200f) {`,
      `      player.y = 200f`,
      `      velocityY = 0f`,
      `    }`,
      `  }`,
      `}`,
      ``,
    ].join('\n');
  }
  return [
    `package ${pkg}`,
    ``,
    `import me.stringdotjar.flixelgdx.Flixel`,
    `import me.stringdotjar.flixelgdx.FlixelState`,
    ``,
    `/**`,
    ` * Your first FlixelState (think of it as one "screen" of your game).`,
    ` * <p>`,
    ` * What to try first:`,
    ` * <p>`,
    ` * Put setup code in create(). It runs once when this state starts.`,
    ` * <p>`,
    ` * Put movement and rules in update(elapsed). It runs every frame.`,
    ` * <p>`,
    ` * When you want a new screen, create another FlixelState subclass and call`,
    ` * Flixel.switchState(new MyOtherState()) from anywhere after Flixel has started.`,
    ` */`,
    `class ${stateCls} extends FlixelState {`,
    ``,
    `  @Override`,
    `  void create() {`,
    `    super.create()`,
    `    Flixel.info("${stateCls} is ready. Add a FlixelSprite here when you want something on screen.")`,
    `  }`,
    ``,
    `  @Override`,
    `  void update(float elapsed) {`,
    `    super.update(elapsed)`,
    `  }`,
    `}`,
    ``,
  ].join('\n');
}

function playStateKotlin(o: GeneratorOptions, stateCls: string): string {
  const pkg = o.packageName;
  if (o.template === 'platformer') {
    return [
      `package ${pkg}`,
      ``,
      `import com.badlogic.gdx.graphics.Color`,
      `import me.stringdotjar.flixelgdx.Flixel`,
      `import me.stringdotjar.flixelgdx.FlixelSprite`,
      `import me.stringdotjar.flixelgdx.FlixelState`,
      `import me.stringdotjar.flixelgdx.input.keyboard.FlixelKey`,
      ``,
      `/**`,
      ` * Tiny starter level with a controllable block.`,
      ` * <p>`,
      ` * Read this like a mini tutorial:`,
      ` * <p>`,
      ` * create() runs once when this state becomes active. Build your scene there.`,
      ` * <p>`,
      ` * update(elapsed) runs every frame. elapsed is seconds since the last frame (use it for smooth motion).`,
      ` * <p>`,
      ` * FlixelSprite is a simple game object with a position (x, y) you can draw.`,
      ` * <p>`,
      ` * makeGraphic builds a solid rectangle so you can run the project before you add art.`,
      ` * <p>`,
      ` * Next experiments: change the color in Color(0xFF2A3CFF.toInt()), resize the sprite, or print logs with`,
      ` * Flixel.info("hello").`,
      ` */`,
      `open class ${stateCls} : FlixelState() {`,
      ``,
      `  private lateinit var player: FlixelSprite`,
      `  private var velocityY = 0f`,
      ``,
      `  override fun create() {`,
      `    super.create()`,
      `    player = FlixelSprite(40f, 80f).apply {`,
      `      makeGraphic(16, 16, Color(0xFF2A3CFF.toInt()))`,
      `    }`,
      `    add(player)`,
      `    Flixel.info("PlatformerState is running. Use arrow keys and space to move and jump.")`,
      `  }`,
      ``,
      `  override fun update(elapsed: Float) {`,
      `    super.update(elapsed)`,
      `    velocityY += 320f * elapsed`,
      `    if (Flixel.keys.pressed(FlixelKey.LEFT)) {`,
      `      player.x -= 90f * elapsed`,
      `    }`,
      `    if (Flixel.keys.pressed(FlixelKey.RIGHT)) {`,
      `      player.x += 90f * elapsed`,
      `    }`,
      `    if (Flixel.keys.justPressed(FlixelKey.SPACE)) {`,
      `      velocityY = -160f`,
      `    }`,
      `    player.y += velocityY * elapsed`,
      `    if (player.y > 200f) {`,
      `      player.y = 200f`,
      `      velocityY = 0f`,
      `    }`,
      `  }`,
      `}`,
      ``,
    ].join('\n');
  }
  return [
    `package ${pkg}`,
    ``,
    `import me.stringdotjar.flixelgdx.Flixel`,
    `import me.stringdotjar.flixelgdx.FlixelState`,
    ``,
    `/**`,
    ` * Your first FlixelState (think of it as one "screen" of your game).`,
    ` * <p>`,
    ` * What to try first:`,
    ` * <p>`,
    ` * Put setup code in create(). It runs once when this state starts.`,
    ` * <p>`,
    ` * Put movement and rules in update(elapsed). It runs every frame.`,
    ` * <p>`,
    ` * When you want a new screen, create another FlixelState subclass and call`,
    ` * Flixel.switchState(MyOtherState()) from anywhere after Flixel has started.`,
    ` */`,
    `open class ${stateCls} : FlixelState() {`,
    ``,
    `  override fun create() {`,
    `    super.create()`,
    `    Flixel.info("${stateCls} is ready. Add a FlixelSprite here when you want something on screen.")`,
    `  }`,
    ``,
    `  override fun update(elapsed: Float) {`,
    `    super.update(elapsed)`,
    `  }`,
    `}`,
    ``,
  ].join('\n');
}

/* --------------------- lwjgl3 launcher source file ----------------------- */
function lwjgl3Launcher(o: GeneratorOptions): Record<string, string> {
  const cls = o.gameName.replace(/\s+/g, '');
  const gameCls = `${cls}Game`;
  const pkg = `${o.packageName}.lwjgl3`;
  const pkgDir = pkg.replace(/\./g, '/');
  if (o.language === 'kotlin') {
    return {
      [`lwjgl3/src/main/kotlin/${pkgDir}/${cls}Lwjgl3Launcher.kt`]: [
        `package ${pkg}`,
        ``,
        `import me.stringdotjar.flixelgdx.backend.lwjgl3.FlixelLwjgl3Launcher`,
        `import ${o.packageName}.${gameCls}`,
        ``,
        `/**`,
        ` * Desktop entry point.`,
        ` * <p>`,
        ` * FlixelLwjgl3Launcher wires libGDX, logging, and window events for you.`,
        ` * <p>`,
        ` * StartupHelper.java lives in this same package as a small vendored helper (damios, Apache-2.0).`,
        ` * It can restart the JVM on some desktops when it needs special flags. If it returns true, stop here.`,
        ` */`,
        `fun main() {`,
        `  if (StartupHelper.startNewJvmIfRequired()) {`,
        `    return`,
        `  }`,
        `  FlixelLwjgl3Launcher.launch(${gameCls}())`,
        `}`,
        ``,
      ].join('\n'),
    };
  }
  if (o.language === 'groovy') {
    return {
      [`lwjgl3/src/main/groovy/${pkgDir}/${cls}Lwjgl3Launcher.groovy`]: [
        `package ${pkg}`,
        ``,
        `import me.stringdotjar.flixelgdx.backend.lwjgl3.FlixelLwjgl3Launcher`,
        `import ${o.packageName}.${gameCls}`,
        ``,
        `/**`,
        ` * Desktop entry point.`,
        ` * <p>`,
        ` * FlixelLwjgl3Launcher wires libGDX, logging, and window events for you.`,
        ` * <p>`,
        ` * StartupHelper.java lives in this same package as a small vendored helper (damios, Apache-2.0).`,
        ` * It can restart the JVM on some desktops when it needs special flags. If it returns true, stop here.`,
        ` */`,
        `final class ${cls}Lwjgl3Launcher {`,
        ``,
        `  static void main(String[] args) {`,
        `    if (StartupHelper.startNewJvmIfRequired()) {`,
        `      return`,
        `    }`,
        `    FlixelLwjgl3Launcher.launch(new ${gameCls}())`,
        `  }`,
        ``,
        `  private ${cls}Lwjgl3Launcher() {}`,
        `}`,
        ``,
      ].join('\n'),
    };
  }
  return {
    [`lwjgl3/src/main/java/${pkgDir}/${cls}Lwjgl3Launcher.java`]: [
      `package ${pkg};`,
      ``,
      `import me.stringdotjar.flixelgdx.backend.lwjgl3.FlixelLwjgl3Launcher;`,
      `import ${o.packageName}.${gameCls};`,
      ``,
      `/**`,
      ` * Desktop entry point.`,
      ` * <p>`,
      ` * FlixelLwjgl3Launcher wires libGDX, logging, and window events for you.`,
      ` * <p>`,
      ` * StartupHelper.java lives in this same package as a small vendored helper (damios, Apache-2.0).`,
      ` * It can restart the JVM on some desktops when it needs special flags. If it returns true, stop here.`,
      ` */`,
      `public final class ${cls}Lwjgl3Launcher {`,
      ``,
      `  public static void main(String[] args) {`,
      `    if (StartupHelper.startNewJvmIfRequired()) {`,
      `      return;`,
      `    }`,
      `    FlixelLwjgl3Launcher.launch(new ${gameCls}());`,
      `  }`,
      ``,
      `  private ${cls}Lwjgl3Launcher() {}`,
      `}`,
      ``,
    ].join('\n'),
  };
}

/* --------------------------- README + gitignore --------------------------- */

interface JdkInstallTips {
  label: string;
  url: string;
  steps: string[];
}

const JDK_TIPS: Record<JdkVendor, JdkInstallTips> = {
  graalvm: {
    label: 'GraalVM Community',
    url: 'https://www.graalvm.org/downloads/',
    steps: [
      'Easiest path: SDKMAN. Then `sdk install java 17-graal`.',
      'Windows : unzip into C:\\graalvm, add the `bin` folder to PATH, set JAVA_HOME.',
      'macOS / Linux: SDKMAN handles PATH automatically.',
    ],
  },
  temurin: {
    label: 'Eclipse Temurin (Adoptium)',
    url: 'https://adoptium.net/temurin/releases/?package=jdk',
    steps: [
      'Windows : run the .msi installer (it sets JAVA_HOME + PATH).',
      'macOS   : brew install --cask temurin@17',
      'Ubuntu  : add the official Adoptium apt repo, then `apt install temurin-17-jdk`.',
    ],
  },
  corretto: {
    label: 'Amazon Corretto',
    url: 'https://docs.aws.amazon.com/corretto/latest/corretto-17-ug/downloads-list.html',
    steps: [
      'Windows : run the .msi installer.',
      'macOS   : brew install --cask corretto@17',
      'Linux   : configure the Amazon apt/yum repo + install `java-17-amazon-corretto-jdk`.',
    ],
  },
  zulu: {
    label: 'Azul Zulu',
    url: 'https://www.azul.com/downloads/?package=jdk',
    steps: [
      'Windows : run the .msi installer.',
      'macOS   : brew install --cask zulu@17',
      'Linux   : use the official Azul apt/yum repo, install `zulu17-jdk`.',
    ],
  },
};

function readme(o: GeneratorOptions): string {
  // Emitted as Markdown at the project root.
  const tips = JDK_TIPS[o.jdkVendor];
  const lines: string[] = [];
  lines.push(`# ${o.gameName}`);
  lines.push('');
  lines.push(
    'Welcome! This folder is a tiny, runnable FlixelGDX starter. The big idea is simple: '
  );
  lines.push(
    'your gameplay code lives in the `core` module, and the `lwjgl3` (or `teavm`) module is only the launcher.'
  );
  lines.push('');
  lines.push('This zip was created by the project generator at');
  lines.push(`https://flixelgdx.github.io/flixelgdx-website/docs/getting-started.`);
  lines.push('');
  lines.push('## 1. Install a JDK');
  lines.push('');
  lines.push(`This project is configured for **${tips.label}**.`);
  lines.push(`Downloads: ${tips.url}`);
  lines.push('');
  lines.push('Quick-start by OS:');
  tips.steps.forEach((s) => lines.push(`  - ${s}`));
  lines.push('');
  lines.push('Confirm the install: `java -version` in a fresh terminal.');
  lines.push('');
  lines.push(`> Any JDK 8+ on PATH is enough to bootstrap Gradle. The build`);
  lines.push(`> auto-downloads the **${tips.label}** toolchain via Gradle's`);
  lines.push(`> Foojay Toolchains Resolver on first run.`);
  lines.push('');
  lines.push('## 2. Open the project');
  lines.push('');
  lines.push(
    'Open this folder as a Gradle project in IntelliJ IDEA, Eclipse, VS Code, or any editor you like. The Gradle tool window (or terminal) is the usual place to run tasks.'
  );
  lines.push('');
  lines.push('## 3. Run your game');
  lines.push('');
  if (o.platforms.includes('desktop')) {
    lines.push('**Desktop:**');
    lines.push('');
    lines.push('    ./gradlew :lwjgl3:run        # macOS / Linux');
    lines.push('    gradlew.bat :lwjgl3:run      # Windows');
    lines.push('');
    lines.push('**Runnable JAR (double-click with Java installed):**');
    lines.push('');
    lines.push('    ./gradlew :lwjgl3:runnableJar');
    lines.push('');
    lines.push(
      `The output is build/pack/${o.gameId}-runnable.jar at the project root (dependencies and assets are bundled inside).`
    );
    lines.push('');
  }
  if (o.platforms.includes('web')) {
    lines.push('**Web:**');
    lines.push('');
    lines.push('    ./gradlew :teavm:run         # TeaVM dev server (macOS / Linux)');
    lines.push('    gradlew.bat :teavm:run       # Windows');
    lines.push('');
  }
  if (o.platforms.includes('desktop')) {
    lines.push('### GraalVM Native Image (optional)');
    lines.push('');
    lines.push(
      'GraalVM Native Image is **off by default** so Gradle sync works with any JDK. To turn it on, set `enableGraalNative=true` in `gradle.properties`, use a GraalVM-capable JDK for the build, then sync again. The `lwjgl3/nativeimage.gradle` script wires nativeCompile, nativeRun, and a small `resource-config.json` refresh from your `assets/` folder.'
    );
    lines.push('');
    lines.push('    ./gradlew :lwjgl3:nativeCompile');
    lines.push('');
    lines.push(
      'Native Image still needs accurate reflection and resource metadata as your game grows. Use tracing or hand-written reachability rules when something is missing at runtime.'
    );
    lines.push('');
    lines.push('### Construo desktop bundles');
    lines.push('');
    lines.push(
      'The `lwjgl3` module also applies Construo. After a normal `./gradlew :lwjgl3:jar`, you can build cross-platform zips (each target downloads its own JDK bundle once):'
    );
    lines.push('');
    lines.push('    ./gradlew :lwjgl3:packageLinuxX64');
    lines.push('    ./gradlew :lwjgl3:packageMacOsAarch64');
    lines.push('    ./gradlew :lwjgl3:packageWinX64');
    lines.push('');
    lines.push('Output zips land in the `dist/` folder at the project root.');
    lines.push('');
  }
  lines.push('This project ships the Gradle 9.5.1 wrapper (see `gradle/wrapper/gradle-wrapper.properties`).');
  lines.push('Gradle wrapper scripts are bundled. You do not need to install Gradle separately.');
  lines.push('First build downloads dependencies (and, if needed, the JDK).');
  lines.push('');
  lines.push('### If Gradle reports an unknown plugin / unresolved plugin artifact');
  lines.push('');
  lines.push('FlixelGDX publishes Gradle plugins to JitPack under coordinates like ');
  lines.push(`\`${JITPACK_FLIXEL_COORD}:flixelgdx-teavm-plugin:<version>\`, while`);
  lines.push('the **plugin IDs** remain `me.stringdotjar.flixelgdx.teavm` (logging:');
  lines.push('`me.stringdotjar.flixelgdx.logging`). The generated `settings.gradle` ');
  lines.push('maps those IDs to JitPack so the `plugins {}` DSL works. ');
  lines.push('If this block is missing, copy it from ');
  lines.push('[COMPILING.md](https://github.com/flixelgdx/flixelgdx/blob/master/COMPILING.md) ');
  lines.push('in the framework repo.');
  lines.push('');
  lines.push('## What you picked');
  lines.push('');
  lines.push(`  - Language        : ${o.language}`);
  lines.push(`  - Java target     : ${o.javaVersion}`);
  lines.push(`  - JDK vendor      : ${tips.label}`);
  lines.push(`  - FlixelGDX       : ${o.flixelVersion} (pulled from JitPack)`);
  lines.push(`  - Default heap    : ${o.heapMb} MB`);
  lines.push(`  - Platforms       : ${o.platforms.join(', ') || 'desktop'}`);
  lines.push(`  - Template        : ${o.template}`);
  lines.push('');
  lines.push('## Project layout');
  lines.push('');
  lines.push('    core/         gameplay code (states, sprites, logic)');
  lines.push(
    '    assets/       shared art, audio, and data (starts empty with .gitkeep so Git keeps the folder)'
  );
  if (o.platforms.includes('desktop')) {
    lines.push(
      '    lwjgl3/       desktop launcher (LWJGL3 / OpenGL)'
    );
  }
  if (o.platforms.includes('web')) {
    lines.push('    teavm/        browser launcher (TeaVM)');
  }
  lines.push('    .editorconfig formatting rules (2-space indent, LF, and trailing whitespace trim)');
  lines.push('    gradlew[.bat] Gradle wrapper bootstrap');
  lines.push('');
  lines.push('## Learn more');
  lines.push('');
  lines.push('  - Pong tutorial : https://flixelgdx.github.io/flixelgdx-website/docs/your-first-project');
  lines.push('  - API reference : https://flixelgdx.github.io/flixelgdx-website/api/');
  lines.push('  - GitHub        : https://github.com/flixelgdx/flixelgdx');
  lines.push('');
  return lines.join('\n');
}

function editorconfig(): string {
  // Mirrors the project's official `.editorconfig` so generated games
  // pick up the same 2-space, LF, trim-trailing-whitespace rules the
  // framework itself uses. Most modern IDEs pick this up automatically.
  return [
    `# https://editorconfig.org`,
    `root = true`,
    ``,
    `[*]`,
    `charset = utf-8`,
    `end_of_line = lf`,
    `insert_final_newline = true`,
    `trim_trailing_whitespace = true`,
    ``,
    `[*.{java,scala,groovy,kt,kts}]`,
    `# 2-space indentation (Google Style Guide Section 4.2)`,
    `indent_style = space`,
    ``,
    `# Even though Google Style Guide Section 2.3 recommends 100 characters,`,
    `# many modern IDEs default to 120 characters, so we follow that convention.`,
    `max_line_length = 120`,
    ``,
    `# Standard Java formatting rules.`,
    `ij_java_use_single_class_imports = true`,
    `ij_java_insert_inner_class_imports = false`,
    `ij_java_class_count_to_use_import_on_demand = 999`,
    `ij_java_names_count_to_use_import_on_demand = 999`,
    `ij_java_packages_to_use_import_on_demand = unset`,
    `ij_java_blank_lines_before_class_end = 0`,
    `ij_java_blank_lines_after_class_header = 1`,
    `ij_java_doc_align_param_comments = false`,
    `ij_java_doc_do_not_wrap_if_one_line = true`,
    `ij_any_keep_simple_blocks_in_one_line = true`,
    ``,
    `# Block formatting (Section 4.1.2)`,
    `ij_java_class_brace_style = end_of_line`,
    `ij_java_method_brace_style = end_of_line`,
    ``,
    `# Space before opening brace (Section 4.6.2)`,
    `ij_java_space_before_class_left_brace = true`,
    `ij_java_space_before_method_left_brace = true`,
    `ij_java_space_before_if_left_brace = true`,
    `ij_java_space_before_while_left_brace = true`,
    `ij_java_space_before_for_left_brace = true`,
    `ij_java_space_before_try_left_brace = true`,
    `ij_java_space_before_catch_left_brace = true`,
    `ij_java_space_before_switch_left_brace = true`,
    `ij_java_space_before_synchronized_left_brace = true`,
    ``,
    `indent_size = 2`,
    ``,
    `[*.gradle]`,
    `indent_size = 2`,
    ``,
    `[*.md]`,
    `trim_trailing_whitespace = false`,
    ``,
  ].join('\n');
}

function gitignore(): string {
  return [
    `.gradle/`,
    `build/`,
    `bin/`,
    `out/`,
    `*.iml`,
    `.idea/workspace.xml`,
    `.idea/tasks.xml`,
    `.idea/caches/`,
    `.idea/libraries/`,
    `.DS_Store`,
    `*.log`,
    ``,
  ].join('\n');
}

function gradleWrapperProperties(): string {
  // Must match the embedded gradle-wrapper.jar in gradleWrapperJar.ts (Gradle 9.5.1).
  return [
    `distributionBase=GRADLE_USER_HOME`,
    `distributionPath=wrapper/dists`,
    `distributionUrl=https\\://services.gradle.org/distributions/gradle-9.5.1-bin.zip`,
    `networkTimeout=10000`,
    `validateDistributionUrl=true`,
    `zipStoreBase=GRADLE_USER_HOME`,
    `zipStorePath=wrapper/dists`,
    ``,
  ].join('\n');
}

/* --------------------------- public entry point --------------------------- */
/**
 * Build the *text* files for a project. The Gradle wrapper jar (binary) is
 * added separately by {@link generateProjectZip} so JSZip can write it with
 * the right encoding.
 */
export function buildProjectFiles(o: GeneratorOptions): Record<string, string> {
  const files: Record<string, string> = {};
  files['README.md'] = readme(o);
  files['.gitignore'] = gitignore();
  files['.editorconfig'] = editorconfig();
  files['assets/.gitkeep'] =
    '# This file keeps the empty assets folder in Git so you can add images, sounds, and data later.\n';
  files['settings.gradle'] = settingsGradle(o);
  files['build.gradle'] = rootBuildGradle(o);
  files['gradle.properties'] = gradleProperties(o);
  files['core/build.gradle'] = coreBuildGradle(o);
  Object.assign(files, gameClassFiles(o));
  if (o.platforms.includes('desktop')) {
    files['lwjgl3/build.gradle'] = lwjgl3BuildGradle(o);
    files['lwjgl3/nativeimage.gradle'] = nativeImageGradle();
    const lwjgl3PkgPath = `${o.packageName}.lwjgl3`.replace(/\./g, '/');
    files[`lwjgl3/src/main/java/${lwjgl3PkgPath}/StartupHelper.java`] =
      buildStartupHelperJava(`${o.packageName}.lwjgl3`);
    Object.assign(files, lwjgl3Launcher(o));
  }
  if (o.platforms.includes('web')) {
    files['teavm/build.gradle'] = teavmBuildGradle(o);
    Object.assign(files, teavmLauncher(o));
  }

  files['gradle/wrapper/gradle-wrapper.properties'] = gradleWrapperProperties();
  return files;
}
