/*
 * Root build script -- intentionally empty.
 *
 * API documentation is generated by scripts/build-api.sh, which applies
 * scripts/docletmd-init.gradle to the framework's own Gradle build so that
 * DocletMD can resolve the full compile classpath automatically.
 */
