import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar shared by every per-module API docs instance. We let
 * Docusaurus auto-generate the tree from the folder structure on disk
 * (the post-processor restructures each module's tree into a clean
 * `input/gamepad/-flixel-input-handler/...` shape).
 *
 * Field-level pages opt out of the sidebar via `sidebar_class_name:
 * flx-hidden-sidebar` in their front-matter (the CSS rule lives in
 * `src/css/custom.css`).
 */
const sidebars: SidebarsConfig = {
  apiSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
