import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * API reference sidebar. One root entry per framework module, each
 * auto-generated from its respective folder. The post-processor at
 * `scripts/postprocess_api.py` lays out the folders so this just
 * works:
 *
 *   api/index.mdx          — welcome page (top of the sidebar)
 *   api/core/...           — Core module tree
 *   api/lwjgl3/...         — Desktop module tree
 *   api/teavm/...          — Web module tree
 *   api/android/...        — Android module tree (may be empty)
 *   api/ios/...            — iOS module tree (may be empty)
 *
 * Field-level pages opt out of the sidebar via `sidebar_class_name:
 * flx-hidden-sidebar` in front-matter (see `src/css/custom.css`).
 */
const sidebars: SidebarsConfig = {
  apiSidebar: [
    'index',
    {
      type: 'category',
      label: 'Core',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'core'}],
    },
    {
      type: 'category',
      label: 'Desktop (LWJGL3)',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'lwjgl3'}],
    },
    {
      type: 'category',
      label: 'Web (TeaVM)',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'teavm'}],
    },
// TODO: Add the mobile modules once we have actually have support for them.
//     {
//       type: 'category',
//       label: 'Android',
//       collapsible: true,
//       collapsed: true,
//       items: [{type: 'autogenerated', dirName: 'android'}],
//     },
//     {
//       type: 'category',
//       label: 'iOS (MobiVM)',
//       collapsible: true,
//       collapsed: true,
//       items: [{type: 'autogenerated', dirName: 'ios'}],
//     },
  ],
};

export default sidebars;
